tap "homebrew/bundle"
tap "d12frosted/emacs-plus"
tap "hashicorp/tap"

brew "ffmpeg"
brew "postgresql@17"
brew "gh"
brew "git"
brew "jq"
brew "llvm"
brew "neofetch"
brew "neovim"
brew "pyenv"
brew "rbenv"
brew "ripgrep"
brew "hashicorp/tap/terraform"
brew "tmux"
brew "tree"
brew "zoxide"
brew "zsh-autosuggestions"
brew "d12frosted/emacs-plus/emacs-plus"

cask "ghostty"
cask "hashicorp-vagrant"
cask "mitmproxy"
cask "vlc"
cask "zed"
